/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author danie
 */
import java.io.*;
import javax.swing.JOptionPane;

public class TelaPressao extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPressao.class.getName());
    
    /**
     * Creates new form TelaPressao
     */
    
    public TelaPressao() {
        initComponents();
        carregarHistorico();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        txtSistolica = new javax.swing.JTextField();
        txtDiastolica = new javax.swing.JTextField();
        chkEstresse = new javax.swing.JCheckBox();
        btnSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHistorico = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Data:");

        jLabel2.setText("Hora:");

        jLabel3.setText("Pressão Sistólica:");

        jLabel4.setText("Pressão Diastólica:");

        txtData.setToolTipText("dd/mm/aaaa");
        txtData.addActionListener(this::txtDataActionPerformed);

        txtHora.setToolTipText("Digite a hora da medição");
        txtHora.addActionListener(this::txtHoraActionPerformed);

        txtSistolica.setToolTipText("Informe a pressão sistólica");
        txtSistolica.addActionListener(this::txtSistolicaActionPerformed);

        txtDiastolica.setToolTipText("Informe a pressão diastólica");

        chkEstresse.setText("Estou em situação de estresse.");
        chkEstresse.addActionListener(this::chkEstresseActionPerformed);

        btnSalvar.setText("Salvar");
        btnSalvar.setToolTipText("Salvar medição");
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);

        txtHistorico.setEditable(false);
        txtHistorico.setColumns(20);
        txtHistorico.setRows(5);
        jScrollPane1.setViewportView(txtHistorico);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkEstresse)
                    .addComponent(btnSalvar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtHora))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDiastolica, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSistolica, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSistolica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDiastolica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkEstresse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
private void carregarHistorico() {

    try {

        File arquivo = new File("medicoes.csv");

        if(!arquivo.exists()) {
            return;
        }

        BufferedReader leitor =
                new BufferedReader(
                        new FileReader(arquivo));

        String linha;

        txtHistorico.setText("");

        while((linha = leitor.readLine()) != null) {

            txtHistorico.append(linha + "\n");
        }

        leitor.close();

    } catch(Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Erro ao carregar histórico."
        );
    }
}
    
    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataActionPerformed

    private void chkEstresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEstresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkEstresseActionPerformed

    private void txtHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraActionPerformed

    private void txtSistolicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSistolicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSistolicaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
try {

    if(txtData.getText().trim().isEmpty() ||
       txtHora.getText().trim().isEmpty() ||
       txtSistolica.getText().trim().isEmpty() ||
       txtDiastolica.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(
            this,
            "Preencha todos os campos."
        );

        return;
    }

    int sistolica =
            Integer.parseInt(
                    txtSistolica.getText());

    int diastolica =
            Integer.parseInt(
                    txtDiastolica.getText());

    String estresse;

    if(chkEstresse.isSelected()) {
        estresse = "Sim";
    } else {
        estresse = "Não";
    }

    String linha =
            txtData.getText() + ";" +
            txtHora.getText() + ";" +
            sistolica + ";" +
            diastolica + ";" +
            estresse;

    FileWriter fw =
            new FileWriter(
                    "medicoes.csv",
                    true);

    PrintWriter pw =
            new PrintWriter(fw);

    pw.println(linha);

    pw.close();

    carregarHistorico();

    JOptionPane.showMessageDialog(
        this,
        "Medição salva com sucesso!"
    );

    txtData.setText("");
    txtHora.setText("");
    txtSistolica.setText("");
    txtDiastolica.setText("");
    chkEstresse.setSelected(false);

}
catch(NumberFormatException e) {

    JOptionPane.showMessageDialog(
        this,
        "Pressões devem conter apenas números."
    );

}
catch(Exception e) {

    JOptionPane.showMessageDialog(
        this,
        "Erro ao salvar arquivo."
    );

}
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPressao().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox chkEstresse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtDiastolica;
    private javax.swing.JTextArea txtHistorico;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtSistolica;
    // End of variables declaration//GEN-END:variables
}
